import {
    UserIcon,
    CogIcon,
    DocumentAddIcon,
    LogoutIcon,
    PencilAltIcon,
} from '@heroicons/react/outline'

export const menu = [
    {
        id: 1,
        icon: <DocumentAddIcon className="h-5 w-5" />,
        href: "/resume-builder",
        label: "Resume Builder",
    },
    {
        id: 2,
        icon: <UserIcon className="h-5 w-5" />,
        href: "/user/profile",
        label: "Profile",
    },
   {
       id: 3,
       icon: <PencilAltIcon className="h-5 w-5" />,
       href: "/feedback",
       label: "Feedback",
   },
    {
        id: 4,
        icon: <LogoutIcon className="h-5 w-5" />,
        href: "/api/auth/logout",
        label: "Logout",
    },
    {
        id: 5,
        icon: <CogIcon className="h-5 w-5" />,
        href: "/user/settings",
        label: "Settings",
    },
]


export const initialFormData = Object.freeze({
    first_name : "",
    last_name : "",
    state : "",
    city : "",
    zip : "",
    email : "",
    phone : "",
    about_me : "",
    school_1 : "",
    school_degree_1 : "",
    school_1_start : "",
    school_1_end : "",
    school_2 : "",
    school_degree_2 : "",
    school_2_start : "",
    school_2_end : "",
    school_3 : "",
    school_degree_3 : "",
    school_3_start : "",
    school_3_end : "",
    job_name_1 : "",
    job_title_1 : "",
    job_date_start_1 : "",
    job_date_end_1 : "",
    job_1_duty : "",
    job_name_2 : "",
    job_title_2 : "",
    job_date_start_2 : "",
    job_date_end_2 : "",
    job_2_duty : "",
    job_name_3 : "",
    job_title_3 : "",
    job_date_start_3 : "",
    job_date_end_3 : "",
    job_3_duty : "",
    skills : "",
    linkedin : "",
    twitter : "",
    github : "",
    internship_1 : "",
    internship_1_year : "",
    internship_2 : "",
    internship_2_year : "",
    internship_3 : "",
    internship_3_year : "",
    volunteer_1 : "",
    volunteer_1_year : "",
    volunteer_2 : "",
    volunteer_2_year : "",
    volunteer_3 : "",
    volunteer_3_year : "",
    username : "",
    img : "",
  });