import {
    UserIcon,
    CogIcon,
    DocumentAddIcon,
    LogoutIcon,
    PencilAltIcon,
} from '@heroicons/react/outline'

export const menu = [
    {
        id: 1,
        icon: <DocumentAddIcon className="h-5 w-5" />,
        href: "/v2/pro-builder",
        label: "Resume Builder",
    },
    {
        id: 2,
        icon: <UserIcon className="h-5 w-5" />,
        href: "/user/profile",
        label: "Profile",
    },
    {
        id: 3,
        icon: <PencilAltIcon className="h-5 w-5" />,
        href: "/feedback",
        label: "Feedback",
    },
    {
        id: 4,
        icon: <LogoutIcon className="h-5 w-5" />,
        href: "/api/auth/logout",
        label: "Logout",
    },
    {
        id: 5,
        icon: <CogIcon className="h-5 w-5" />,
        href: "/user/settings",
        label: "Settings",
    },
];

export const majors = {
    Agriculture: [
        "Agriculture",
        "Agribusiness Operations",
        "Agricultural Management",
        "Agricultural Economics",
        "Agricultural Mechanization",
        "Agricultural Production",
        "Agronomy & Crop Science",
        "Animal Sciences",
        "Food Sciences & Technology",
        "Horticulture Management",
        "Horticulture Science",
        "Natural Resources Conservation",
        "Environmental Science",
        "Forestry",
        "Natural Resources Management",
        "Wildlife & Wildlands Management"
    ],
    Architecture: [
        "Architecture",
        "Architectural Environmental Design",
        "City/Urban/Regional Planning",
        "Interior Architecture",
        "Landscape Architecture"
    ],
    Multidisciplinary: [
        "Area Studies",
        "Asian Area Studies",
        "European Area Studies",
        "Latin American Area Studies",
        "North American Area Studies",
        "Ethnic & Minority Studies",
        "African American Studies",
        "Native American Studies",
        "Latino/Chicano Studies",
        "Women’s Studies",
        "Liberal Arts & General Studies",
        "Library Science",
        "Multi/Interdisciplinary Studies"
    ],
    Arts: [
        "Art General",
        "Art History",
        "Criticism & Conservation",
        "Fine/Studio Arts",
        "Cinema/Film",
        "Cinematography",
        "Dance",
        "Design & Visual Communications",
        "Fashion/Apparel Design",
        "Graphic Design",
        "Industrial Design",
        "Interior Design",
        "Performance",
        "Music",
        "Theory & Composition",
        "Photography",
        "Theatre Arts/Drama"
    ],
    Communications: [
        "Communications",
        "Advertising",
        "Digital Communications",
        "Journalism",
        "Broadcast",
        "Broadcasting Technology",
        "Journalism",
        "Print",
        "Mass Communications",
        "Public Relations",
        "Organizational Communication",
        "Radio & Television Broadcasting",
        "Communications Technology",
        "Graphic Equipment Operation",
        "Multimedia Effects",
    ],
    Business: [
        "Accounting Technician",
        "Business Administration & Management",
        "Hotel Management",
        "Human Resources Development",
        "Human Resources Management",
        "International Business Management",
        "Industrial Relations",
        "Logistics & Materials Management",
        "Marketing Management & Research",
        "Office Supervision & Management",
        "Operations Management & Supervision",
        "Organizational Behavior",
        "Purchasing Management",
        "Food Services Management",
        "Small Business Management",
        "Tourism Management"
    ],
    Community: [
        "Child Care Services Management",
        "Child Development",
        "Consumer & Family Economics",
        "Food & Nutrition",
        "Textile & Apparel",
        "Recreation",
        "Kinesiology",
        "Health & Physical Education",
        "Sport & Fitness Administration",
        "Personal Services, General",
        "Cosmetology/Hairstyling",
        "Culinary Arts/Chef Training",
        "Funeral Services & Mortuary Science",
        "Protective Services, General",
        "Corrections",
        "Criminal Justice",
        "Fire Protection Technology",
        "Law Enforcement",
        "Military Technologies",
        "Public Administration",
        "Community Organization & Advocacy",
        "Public Administration",
        "Social Work"
    ],
    Computer: [
        "Information Sciences",
        "Computer Networking",
        "Computer Science",
        "Computer Software",
        "Computer System Administration",
        "Data Management Technology",
        "Information Science",
        "Webpage Design",
        "Mathematics",
        "Applied Mathematics",
        "Statistics",
    ],
    Education: [
        "Counseling & Student Services",
        "Educational Administration",
        "Special Education",
        "Teacher Education, General",
        "Curriculum & Instruction",
        "Early Childhood Education",
        "Elementary Education",
        "Junior High/Middle School Education",
        "Postsecondary Education",
        "Secondary Education",
        "Teacher Assisting/Aide Education",
        "Teacher Education, Subject-Specific*",
        "Agricultural Education",
        "Art Education",
        "Business Education",
        "Career & Technical Education",
        "English-as-a-Second-Language Education",
        "English/Language Arts Education",
        "Foreign Languages Education",
        "Health Education",
        "Mathematics Education",
        "Music Education",
        "Physical Education & Coaching",
        "Science Education",
        "Social Studies/Sciences Education",
    ],
    Engineering: [
        "Engineering (Pre-Engineering)",
        "Aerospace/Aeronautical Engineering",
        "Agricultural/Bioengineering",
        "Architectural Engineering",
        "Biomedical Engineering",
        "Chemical Engineering",
        "Civil Engineering",
        "Computer Engineering",
        "Construction Engineering",
        "Electrical",
        "Communications Engineering",
        "Environmental Health Engineering",
        "Industrial Engineering",
        "Mechanical Engineering",
        "Nuclear Engineering"
    ],
    Language: [
        "English & Foreign Languages",
        "English Language & Literature",
        "American/English Literature",
        "Creative Writing",
        "Public Speaking",
        "Foreign Literatures",
        "Asian Languages & Literatures",
        "Classical/Ancient Languages",
        "Comparative Literature",
        "French Language & Literature",
        "German Language & Literature",
        "Linguistics",
        "Middle Eastern Languages",
        "Spanish Language & Literature"
    ],
    HEALTH: [
        "Chiropractic (Pre-Chiropractic)",
        "Dental Hygiene",
        "Dentistry (Pre-Dentistry)",
        "Emergency Medical Technology",
        "Health-Related Professions & Services",
        "Athletic Training",
        "Public Health",
        "Health/Medical Technology",
        "Medical Laboratory Technology",
        "Medical Radiologic Technology",
        "Nuclear Medicine Technology",
        "Respiratory Therapy Technology",
        "Surgical Technology",
        "Medicine (Pre-Medicine)",
        "Nursing",
        "Practical/Vocational (LPN)",
        "Registered (BS/RN)"
    ],
    PHILOSOPHY: [
        "Philosophy",
        "Religion",
        "Theology",
        "Bible/Biblical Studies",
        "Divinity/Ministry",
        "Religious Education"
    ],
    CONSTRUCTION: [
        "Aviation & Airway Science",
        "Aircraft Piloting & Navigation",
        "Aviation Management & Operations",
        "Construction Trades",
        "Mechanics & Repairers",
        "Aircraft Mechanics/Technology",
        "Autobody Repair/Technology",
        "Automotive Mechanics/Technology",
        "Avionics Technology",
        "Diesel Mechanics/Technology",
        "Electrical/Electronics Equip Repair",
        "Heating/Air Cond/Refrig Install/Repair",
        "Precision Production Trades",
        "Machine Tool Technology",
        "Welding Technology",
        "Transportation & Materials Moving"
    ],
    PHYSICAL: [
        "Biology",
        "Biochemistry & Biophysics",
        "Cell/Cellular Biology",
        "Computer Science",
        "Ecology",
        "Genetics",
        "Marine/Aquatic Biology",
        "Microbiology & Immunology",
        "Zoology",
        "Physical Sciences",
        "Astronomy",
        "Atmospheric Sciences & Meteorology",
        "Chemistry",
        "Geological & Earth Sciences",
        "Physics"
    ],
    LAW: [
        "Legal Studies",
        "Court Reporting",
        "Law (Pre-Law)",
        "Legal Administrative",
        "Paralegal/Legal Assistant",
        "Social Sciences",
        "Anthropology",
        "Criminology",
        "Economics",
        "Geography",
        "History",
        "International Relations & Affairs",
        "Political Science & Government",
        "Psychology",
        "Clinical & Counseling",
        "Psychology",
        "Sociology",
        "Urban Studies/Urban Affairs"
    ]
}
